# .github/workflows/ci-coverage.yml

name: Upload Coverage

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  upload-coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true

    # Permissions are needed for the codecov-action to post results
    # back to a pull request or checks.
    permissions:
      contents: read       # to read commit data
      checks: write        # to post status checks
      pull-requests: write # to comment on pull requests

    steps:
      - name: 📥 Download Coverage Artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          name: coverage-report-${{ github.sha }}
          path: ${{ github.workspace }}/

      - name: 🧾 Upload coverage
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}