# .github/workflows/ci-coverage.yml
name: Upload Coverage

on:
  workflow_call:

jobs:
  upload-coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true

    steps:
      - name: 📥 Download Coverage Artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          name: coverage-report-${{ github.sha }}
          path: ${{ github.workspace }}/

      - name: 🧾 Upload coverage
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}