# .github/workflows/ci-main.yml

# Runs a packaging build and then performs a release dry-run (no NuGet push / no GitHub Release).
# Trigger from the UI and pass any version (e.g., v1.2.3-rc) to validate the pipeline end-to-end.

name: Release Plan (Dry Run) CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: >-
          Version to validate (e.g., v1.2.3-rc),
          used for tag checks during dry-run
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-dryrun
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pack:
    name: 📦 Pack (build artifacts)
    uses: ./.github/workflows/ci-pack.yml
    permissions:
      contents: read
      checks: write

  plan-release:
    name: 🧭 Release Plan
    needs: pack
    uses: ./.github/workflows/ci-release.yml
    permissions:
      contents: read
    with:
      dry-run: true
      version: ${{ inputs.version }}